name: Build and smoketest

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Compile the plugin, upload to Actions
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean build --info --stacktrace

      - name: Upload artifacts to Actions
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs

  compile_samples:
    name: Compile demo
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java ${{matrix.java_version}}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "${{matrix.java_version}}"

      - name: Build demo with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean build --info --stacktrace -Dminivan.refreshDependencies=true
          build-root-directory: "./demo"